compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: eslint
  - level: discard
    pattern: "@algolia"

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.0.cjs
