/**
 * @copyright OpenISP, Inc.
 * @license AGPL-3.0
 * @author Teffen Ellis, et al.
 */

import { JSONSchemaID } from "@isp.nexus/core"
import type { FRN, Form499ID, ProviderID } from "@isp.nexus/fcc"
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { EmailContact, PhoneContact, PointOfContact, PostalAddress } from "@isp.nexus/mailwoman"
import type { OrganizationClassification } from "./classification.js"

//#region Schema

export const $Organization = JSONSchemaID("Organization")
export type $Organization = typeof $Organization

/**
 * A telecommunications entity registered with the Federal Communications Commission (FCC).
 *
 * @title FCC Entity
 * @public
 * @requires {@linkcode PostalAddress}
 * @requires {@linkcode PhoneContact}
 * @requires {@linkcode EmailContact}
 * @requires {@linkcode PointOfContact}
 */
export interface Organization {
	//#region ID Properties

	/**
	 * The ID of the Point of Contact.
	 *
	 * @title ID
	 */
	id: string

	/**
	 * The FCC Registration Number (FRN) of the entity.
	 *
	 * @title FCC Registration Number
	 */
	frn?: FRN

	/**
	 * The unique 6-digit code generated by the FCC that identifies each service provider.
	 *
	 * @title Fixed Broadband Provider ID
	 *
	 * @see {@linkcode ProviderID}
	 */
	providerID?: ProviderID | null

	/**
	 * The FRN of the entity that proceeded this one, if applicable.
	 *
	 * This is used when an entity is acquired, marked defuct, or merges with another entity.
	 *
	 * @title Predecessor FRN
	 */
	predecessorFRN?: FRN

	/**
	 * The entity that proceeded this one, if applicable.
	 *
	 * @ignore
	 * @internal
	 * @title Predecessor
	 */
	predecessor?: Organization | null

	/**
	 * The FRN of the entity that succeeded this one, if applicable.
	 *
	 * This is used when an entity is acquired, marked defuct, or merges with another entity.
	 *
	 * @title Successor FRN
	 */
	successorFRN?: FRN

	/**
	 * The entity that succeeded this one, if applicable.
	 *
	 * @ignore
	 * @internal
	 * @title Successor
	 */
	successor?: Organization | null

	/**
	 * The FCC Form 499 ID of the entity.
	 *
	 * @title FCC Form 499 ID
	 * @see {@linkcode Form499ID}
	 */
	form499ID?: Form499ID | null

	//#endregion

	//#region Timestamps

	/**
	 * The timestamp when the Point of Interest was created.
	 *
	 * @type string
	 * @title Updated At
	 * @format date-time
	 */
	createdAt?: Date

	/**
	 * The timestamp when the Point of Interest was updated.
	 *
	 * @type string
	 * @title Updated At
	 * @format date-time
	 */
	updatedAt?: Date

	/**
	 * The date on which the entity became inactive, if applicable.
	 *
	 * @type string
	 * @title Inactive At
	 * @format date
	 */
	inactiveAt?: Date

	/**
	 * The date the entity was registered with the FCC.
	 *
	 * @type string
	 * @title Registered At
	 * @format date-time
	 */
	registeredAt?: Date

	/**
	 * The date the entity last filed its Form 499.
	 *
	 * @type string
	 * @title Form 499 Filed At
	 * @format date
	 */
	form499FiledAt?: Date

	//#endregion

	//#region Entity Properties

	/**
	 * The legal name of the entity as registered with the FCC.
	 *
	 * @title Legal Name
	 * @TJS-examples ["Comcast Cable Communications, LLC", "Verizon Wireless", "AT&T Mobility"]
	 * @maxLength 255
	 */
	legalName?: string | null

	/**
	 * The sanitized name of the organization, for use identifying the organization.
	 *
	 * @title Sanitized Legal Name
	 */
	sanitizedLegalName?: string | null

	/**
	 * The EIN of the organization, if any.
	 *
	 * @title EIN
	 */
	EIN?: string | null

	/**
	 * The name under which the entity does business, if different from the legal name.
	 *
	 * @title Doing Business As Name
	 * @TJS-examples ["Xfinity", "Verizon", "AT&T"]
	 */
	doingBusinessAs?: string | null

	/**
	 * @title Classifications
	 *
	 * One or more classes which apply to the entity.
	 */
	classifications?: Set<OrganizationClassification>

	/**
	 * The name of the entity's holding company, if applicable.
	 *
	 * @title Holding Company
	 * @TJS-examples ["Comcast Corporation", "Verizon Communications", "AT&T Inc."]
	 */
	holdingCompany?: string | null

	/**
	 * The associated ID of the entity's headquarters address.
	 *
	 * @format uuid
	 * @title Headquarters Address ID
	 */
	headquartersAddressID?: string | null

	/**
	 * The physical address of the entity's headquarters.
	 *
	 * @title Headquarters Address
	 */
	headquartersAddress?: PostalAddress | null

	/**
	 * The associated ID of the entity's primary contact person.
	 *
	 * @title Primary Contact ID
	 * @format uuid
	 */
	primaryContactID?: string | null

	/**
	 * The primary contact person for the entity.
	 *
	 * @title Primary Contact
	 */
	primaryContact?: PointOfContact | null

	/**
	 * The associated ID of the entity's Washington DC agent.
	 *
	 * @title Washington DC Agent ID
	 */
	dcAgentID?: string | null

	/**
	 * An agent in Washington DC who can accept service of process and official notices for the
	 * company.
	 *
	 * This is required for all telecommunications carriers that participate in the Universal Service
	 * Fund.
	 *
	 * @title Washington DC Agent
	 */
	dcAgent?: PointOfContact | null

	/**
	 * The associated ID of the entity's Washington DC agent organization.
	 *
	 * @title Washington DC Agent Organization ID
	 */
	dcAgentOrganizationID?: string | null

	/**
	 * An organization associated with the Washington DC agent.
	 *
	 * @title Washington DC Agent Organization
	 */
	dcAgentOrganization?: Organization | null

	/**
	 * The associated ID of the customer point of contact.
	 *
	 * @type string
	 * @title Customer Point of Contact ID
	 * @format uuid
	 */
	customerServiceContactID?: string | null

	/**
	 * @title Customer Service Point of Contact
	 *
	 * The point of contact for customer inquiries, if different from the primary contact.
	 */
	customerServiceContact?: PointOfContact

	//#endregion
}
